### ISSUE TITLE
in_filters argument is not used in `upsample_block()` function.

### ISSUE THREAD

**Issue by philyoun** [henry32144/pggan-tensorflow#2] opened 2021-06-29 00:27 UTC
Hi henry, I'm reviewing your PGGAN project.

In your
https://github.com/henry32144/pggan-tensorflow/blob/master/PGGAN-Tensorflow.ipynb

the function `upsample_block()` has a `in_filters` argument, but it is not used.

It only uses `filters` argument, and it does not produce error due to 'last part is done with the `filters` argument' .

But I think the first `EqualizeLearningRate(keras.layers.Conv2D(filters, ...)` should be `EqualizeLearningRate(keras.layers.Conv2D(in_filters, ...)`.

Please check this out. Thank you.

**Comment by henry32144** [comment] 2021-06-29 06:37
Ok, I'll check that. Thank you for letting me know!

**Comment by henry32144** [comment] 2021-07-12 12:14
I think the problem should be fixed with the latest commit. Feel free to reopen it if the problem is still there.

**Closed as completed by henry32144** 2021-07-12 12:14 UTC
